version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: vending_machine_api_db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - postgres.env
    ports:
      - 5432:5432

volumes:
  postgres-data:
